name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-branch:
    runs-on: ubuntu-latest

    timeout-minutes: 2
    concurrency:
      group: ci-check-branch-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          fetch-depth: 0

      - name: Check if the PR's branch is updated
        if: ${{ github.event_name == 'pull_request' }}
        uses: osl-incubator/gh-check-pr-is-updated@1.0.0
        with:
          remote_branch: origin/main
          pr_sha: ${{ github.event.pull_request.head.sha }}

  tests:
    strategy:
      matrix:
        python_version:
          - "3.8.1"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"

        os:
          - "ubuntu"
          - "macos"
          # - 'windows'  # note: makim doesn't have support for windows yet

    runs-on: ${{ matrix.os }}-latest

    timeout-minutes: 10
    concurrency:
      group: ci-tests-${{ matrix.os }}-${{ matrix.python_version }}-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Install MacOS extra tools and add extra setup
        if: ${{ matrix.os == 'macos' }}
        run: |
          sudo mkdir -p /tmp
          sudo chmod 777 /tmp

          brew install gnu-sed
          echo 'export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"' >> ~/.bashrc
          echo 'export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"' >> ~/.bash_profile

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          environment-file: conda/dev.yaml
          channels: conda-forge,nodefaults
          activate-environment: envers
          auto-update-conda: true
          conda-solver: libmamba
          python-version: "${{ matrix.python_version }}"

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry check
          poetry install

      - name: Run tests
        run: |
          makim tests.unit

      - name: Run smoke tests
        run: |
          makim tests.smoke

  linter-and-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        shell: bash -l {0}

    concurrency:
      group: ci-linter-docs-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          environment-file: conda/dev.yaml
          channels: conda-forge,nodefaults
          activate-environment: envers
          auto-update-conda: true
          conda-solver: libmamba
          python-version: "3.8.1"

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry check
          poetry install

      - name: Test documentation generation
        run: makim docs.build

      - name: Run style checks
        if: success() || failure()
        run: makim tests.linter
